---
name: CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.6"
            machine: ubuntu-20.04
          - python-version: "3.7"
            machine: ubuntu-22.04
          - python-version: "3.8"
            machine: ubuntu-22.04
          - python-version: "3.9"
            machine: ubuntu-22.04
          - python-version: "3.10"
            machine: ubuntu-22.04
          - python-version: "3.11"
            machine: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: |
          python -m tox
      - uses: codecov/codecov-action@v3
  publish:
    runs-on: ubuntu-latest
    needs:
      - tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Build a binary wheel and a source tarball
        run: pipx run build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
